### ISSUE TITLE
FormatterPool does not provide ability to create new formatters

### ISSUE THREAD

**Issue by AlexZhembl** [netcosports/Alidade#2]
If you want to implement ex. `MeasurementFormatter`, you must privide
`func cached(format: String, locale: Locale = .current) -> DateFormatter`
included extensions contains this
`return FormatterPool.formatter(format: format, locale: locale)`
But `FormatterPool` is `fileprivate final class`
so others cannot realize new formatted-pool formatters.
possible solutions:

- move this class to public
- add extensions to all 9 standart formatters:
https://developer.apple.com/documentation/foundation/formatter

**Comment by dDomovoj** [comment]
@AlexZhembl should be done in v.1.1.0
